/*
 * generated by Xtext 2.13.0
 */
package com.metagamedsl.individual.ide


/**
 * Use this class to register ide components.
 */
class MetaGameLanguageIdeModule extends AbstractMetaGameLanguageIdeModule {
}
